name: Hurl Tests

on: push

jobs:
  api-test-hurl:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v5

      # Installation de Hurl
      - name: Install Hurl
        run: |
          curl -L https://github.com/Orange-OpenSource/hurl/releases/latest/download/hurl-linux-x86_64.tar.gz -o hurl.tar.gz
          tar -xzf hurl-linux-x86_64.tar.gz
          chmod +x hurl/bin/hurl
          sudo mv hurl/bin/hurl /usr/local/bin/

      # Exécution des tests Hurl
      - name: Run Hurl Tests
        run: |
          hurl --test --report-html report-html --output results.json tests/*.hurl

      # Upload des résultats
      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: hurl-test-results
          path: |
            results.json
            report-html
